ALTER TABLE dbo.OFFENSE
ADD FOREIGN KEY (gid)
REFERENCES GAME(gid)
;
ALTER TABLE dbo.DEFENSE
ADD FOREIGN KEY (gid)
REFERENCES GAME(gid)
;
ALTER TABLE dbo.KICKER
ADD FOREIGN KEY (gid)
REFERENCES GAME(gid)
;
ALTER TABLE dbo.REDZONE
ADD FOREIGN KEY (gid)
REFERENCES GAME(gid)
;
ALTER TABLE dbo.INJURY
ADD FOREIGN KEY (gid)
REFERENCES GAME(gid)
;
ALTER TABLE dbo.PASS
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.RUSH
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.TD
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.FGXP
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.CONV
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.PUNT
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.CHART
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.SACK
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.TACKLE
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.PENALTY
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.FUMBLE
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.INTERCPT
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.BLOCK
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.SAFETY
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.KOFF
ADD FOREIGN KEY (PID)
REFERENCES PLAY(PID)
;
ALTER TABLE dbo.TEAM
ADD FOREIGN KEY (GID)
REFERENCES GAME (GID)
;
ALTER TABLE dbo.OFFENSE
ADD FOREIGN KEY (PLAYER)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.DEFENSE
ADD FOREIGN KEY (PLAYER)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.KICKER
ADD FOREIGN KEY (PLAYER)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.REDZONE
ADD FOREIGN KEY (PLAYER)
REFERENCES PLAYER (PLAYER)
;
delete 
from INJURY 
where player not in 
   (select distinct (PLAYER) FROM PLAYER)
;
ALTER TABLE dbo.INJURY
ADD FOREIGN KEY (PLAYER)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.PASS
ADD FOREIGN KEY (PSR)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.PASS
ADD FOREIGN KEY (TRG)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.PASS
ADD FOREIGN KEY (DFB)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.RUSH
ADD FOREIGN KEY (BC)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.TD
ADD FOREIGN KEY (PLAYER)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.FGXP
ADD FOREIGN KEY (FKICKER)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.CONV
ADD FOREIGN KEY (BC)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.CONV
ADD FOREIGN KEY (PSR)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.CONV
ADD FOREIGN KEY (TRG)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.PUNT
ADD FOREIGN KEY (PUNTER)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.PUNT
ADD FOREIGN KEY (PR)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.SACK
ADD FOREIGN KEY (SK)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.SACK
ADD FOREIGN KEY (QB)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.TACKLE
ADD FOREIGN KEY (TCK)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.PENALTY
ADD FOREIGN KEY (PEN)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.FUMBLE
ADD FOREIGN KEY (FUM)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.FUMBLE
ADD FOREIGN KEY (FRCV)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.FUMBLE
ADD FOREIGN KEY (FORC)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.INTERCPT
ADD FOREIGN KEY (PSR)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.INTERCPT
ADD FOREIGN KEY (INTS)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.BLOCK
ADD FOREIGN KEY (BLK)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.BLOCK
ADD FOREIGN KEY (BRCV)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.SAFETY
ADD FOREIGN KEY (SAF)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.KOFF
ADD FOREIGN KEY (KICKER)
REFERENCES PLAYER (PLAYER)
;
ALTER TABLE dbo.KOFF
ADD FOREIGN KEY (KR)
REFERENCES PLAYER (PLAYER)
;



